Require postal code if available
troyhunt/password-purgatory-api pull request #10
Opened 2022-03-10 07:46 UTC by olikami

If the postal code is available through `request.cf` it should be a requirement for the password.

2022-03-10 13:07 UTC, teh-maxh commented
Including the postcode in the error message is probably too helpful.

2022-03-10 13:11 UTC, olikami commented
This probably works for countries where the IP address data is great, but in my case it gave me the postal code of my ISP. I do want the spammers to get on to the next level 😈 .

2022-03-10 19:10 UTC, Greenlio commented
It already has any US postal code, having their ISP postal code would be kinda weird lol?

2022-03-17 20:08 UTC, BitPatty commented
Tried this a few times with different ISPs / devices and it never matched my location. In around 1/3 of attempts it got the coordinates of a nearby city. On cellular the data is completely off.

Even if it were accurate, IMO users shouldn't have to enter any personal/linkable metadata.

2022-03-25 07:55 UTC, MichaelNMaggs commented
Conflicts with "Must have US Zip code" message

2022-08-04 23:06 UTC, Saiv46 requested changes

2022-08-04 23:06 UTC, Saiv46 commented on index.js
> +  }
```suggestion
  else if (request.cf.postalCode && !password.match(new RegExp(request.cf.postalCode.slice(0, 3) + '\d{2,4}')) {
    badPasswordMessage = `Password must contain your postal code (${request.cf.postalCode.slice(0, 3)}**)`
  }
```

As people pointed out here - postal codes does not match exact location. Yet they still match the country and city, so why not check first 3 digits instead?

2022-08-04 23:11 UTC, Saiv46 commented on index.js
> +  }
In US such accuracy would give down to state, in Japan/Russia/Ukraine - down to city. In EU it still completely misses though

2022-08-05 01:03 UTC, troyhunt commented
I've decided to drop post code out altogether in https://github.com/troyhunt/password-purgatory-api/commit/6f274b625e3cf60d52436adda2c83f78e2b622c6 as it's just too geographically specific, better we have criteria that is more globally inclusive.

2022-08-05 01:03 UTC, closed without merging